[workspace]
authors = ["huyha1314 <hagiahuy311@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "suran_16S"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
# --- Core Pipeline Tasks ---
generate_samples = "bash script/generate_samples_tsv.sh data ./sample.tsv"
generate_metadata = "Rscript script/convert_metadata.R"
check_md5 = "bash script/check_md5.sh data"
qc_trim = "bash script/01_qc_trim.sh"
dada2 = "Rscript script/02_dada2.R"
phyloseq = "Rscript script/03_phyloseq_prep.R"
stats = "Rscript script/04_longitudinal_stats.R"
network = "Rscript script/05_network_analysis.R"
download_db = "bash script/download_db.sh"
picrust2 = "bash script/06_picrust2.sh"
qc_trim_long = "bash script/01_qc_trim_longread.sh"
classify_long = "Rscript script/02_minimap2_classify.R"


# --- New Visualization & Reporting Tasks ---
vis_tax = "Rscript vis/1.tax.R"
vis_alpha = "Rscript vis/2.alpha.R"
vis_beta = "Rscript vis/3.beta.R"
vis_rare = "Rscript vis/4.rarefaction.R"
vis_diff = "Rscript vis/5.differential.R"
vis_func = "Rscript vis/6.function.R"

# --- Automation Tasks ---
build_report_env = "bash script/07_vis.sh"
all = "bash master.sh"

[dependencies]
# --- Core Dependencies ---
fastqc = ">=0.12.1,<0.13"
cutadapt = ">=5.2,<6"
multiqc = ">=1.35,<2"
bioconductor-dada2 = ">=1.38.0,<2"
bioconductor-phyloseq = ">=1.54.0,<2"
r-vegan = ">=2.7_3,<3"
r-tidyverse = ">=2.0.0,<3"
r-ggpubr = ">=0.6.3,<0.7"
r-lme4 = ">=2.0_1,<3"
r-lmertest = ">=3.2_1,<4"
r-rmarkdown = ">=2.31,<3"
r-knitr = ">=1.51,<2"
r-openxlsx = ">=4.2.8.1,<5"
r-cowplot = ">=1.2.0,<2"
r-dt = ">=0.34.0,<0.35"
picrust2 = ">=2.6.3,<3"
parallel = ">=20260422,<20260423"

# --- New Interactivity & Rendering Dependencies ---
quarto = ">=1.4,<2"
r-plotly = ">=4.10.4,<5"
r-htmlwidgets = ">=1.6.4,<2"
r-htmltools = ">=0.5.8.1,<1"
r-matrixstats = ">=1.3.0,<2"
bioconductor-decipher = ">=3.6.0,<4"
r-phangorn = ">=2.12.1,<3"
r-ape = ">=5.8_1,<6"
fasttree = ">=2.2.0,<3"
bioconductor-deseq2 = ">=1.50.2,<2"
bioconductor-ancombc = ">=2.12.0,<3"
bioconductor-microbiome = ">=1.32.0,<2"
minimap2 = ">=2.28,<3"
samtools = ">=1.19,<2"
filtlong = ">=0.2.1,<0.3"
nanoplot = ">=1.42.0,<2"
emu = ">=3.6.2,<4"
kraken2 = ">=2.17.1,<3"
bracken = ">=3.1,<4"
osfclient = ">=0.0.5,<0.0.6"
kraken-biom = ">=1.2.0,<2"
barrnap = ">=1.10.6,<2"
bioconductor-decontam = ">=1.30.0,<2"


